//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Prototype.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBank
    {
        public BloodBank()
        {
            this.DonateBloods = new HashSet<DonateBlood>();
            this.RecieveBloods = new HashSet<RecieveBlood>();
        }
    
        public int Id { get; set; }
        public string BloodName { get; set; }
        public int Qty { get; set; }
    
        public virtual ICollection<DonateBlood> DonateBloods { get; set; }
        public virtual ICollection<RecieveBlood> RecieveBloods { get; set; }
    }
}
