//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Prototype.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonateBlood
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BloodId { get; set; }
        public int StatusId { get; set; }
        public int Qty { get; set; }
        public System.DateTime DonatedOn { get; set; }
    
        public virtual BloodBank BloodBank { get; set; }
        public virtual StatusSetting StatusSetting { get; set; }
        public virtual User User { get; set; }
    }
}
