//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Prototype.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BBMSEntities1 : DbContext
    {
        public BBMSEntities1()
            : base("name=BBMSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BloodBank> BloodBanks { get; set; }
        public DbSet<Chat> Chats { get; set; }
        public DbSet<DonateBlood> DonateBloods { get; set; }
        public DbSet<RecieveBlood> RecieveBloods { get; set; }
        public DbSet<StatusSetting> StatusSettings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
    }
}
