//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Prototype.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Chats = new HashSet<Chat>();
            this.Chats1 = new HashSet<Chat>();
            this.DonateBloods = new HashSet<DonateBlood>();
            this.RecieveBloods = new HashSet<RecieveBlood>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public System.DateTime Dob { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Gender { get; set; }
        public System.DateTime LastDonatedOn { get; set; }
        public int UserTypeID { get; set; }
        public string Password { get; set; }
        public string BloodGroup { get; set; }
    
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<Chat> Chats1 { get; set; }
        public virtual ICollection<DonateBlood> DonateBloods { get; set; }
        public virtual ICollection<RecieveBlood> RecieveBloods { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
